apiVersion: v1
kind: Service
metadata:
  name: parkos
  namespace: example
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: parkos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
    